#!/usr/bin/env bash

# Increment the patch version only if on main branch.
current_branch=$(git branch --show-current)
if [ "$current_branch" = "main" ]; then
  yarn version --patch -m "Bump version to %s"
fi
