#!/usr/bin/env bash

# Increment the patch version only if on main branch and there are meaningful changes.
current_branch=$(git branch --show-current)
if [ "$current_branch" = "main" ]; then
  # Check for any changes excluding version bump in package.json
  if ! git diff --quiet HEAD -- . ':(exclude)package.json' ||
    git diff HEAD -- package.json | grep -qv '"version":'; then
    echo "Changes detected. Incrementing version."
    yarn version --patch
  else
    echo "No meaningful changes detected. Skipping version increment."
  fi
fi
